### ISSUE TITLE
Make github-analytics take in account reactions on issues

### ISSUE THREAD

**Issue by zakkak** [kabitakis/github-analytics#20]

**Comment by irinikp** [comment]
#22 I guess this issue can close now

**Comment by kabitakis** [comment]
Well, it doesn't count the votes correctly. Check https://github.com/devstaff-crete/DevStaff-Heraklion/issues/179 for example. It has 2 reaction votes and 4 comment votes. The app counts only 4 comment votes. A valid output would be 6 since each vote comes from a different voter.

**Comment by irinikp** [comment]
No, the app now shows 6 votes on this issue

**Comment by kabitakis** [comment]
Check the results here: https://analytics.devstaff.gr/. It gives 4 votes for issue 179.
Any uncommitted changes maybe?

**Comment by kabitakis** [comment]
My bad. Caching issues :) I'm closing this one.
